"""empty message

Revision ID: 056017b8d1a4
Revises: cfb77ed3c2ed
Create Date: 2019-03-05 21:46:10.328981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056017b8d1a4'
down_revision = 'cfb77ed3c2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education_program')
    # ### end Alembic commands ###
