"""empty message

Revision ID: 280b88c9c555
Revises: bc92eafed48b
Create Date: 2019-03-10 14:45:13.000570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280b88c9c555'
down_revision = 'bc92eafed48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ZYN',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('discipline_name', sa.String(length=128), nullable=True),
    sa.Column('know', sa.String(length=255), nullable=True),
    sa.Column('can', sa.String(length=255), nullable=True),
    sa.Column('own', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.Column('know', sa.String(length=255), nullable=True),
    sa.Column('can', sa.String(length=255), nullable=True),
    sa.Column('own', sa.String(length=255), nullable=True),
    sa.Column('themes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('discipline_name', sa.String(length=128), nullable=True),
    sa.Column('parts_id', sa.Integer(), nullable=True),
    sa.Column('parts_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('discipline_name', sa.String(length=128), nullable=True),
    sa.Column('parts_id', sa.Integer(), nullable=True),
    sa.Column('themes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('program', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profstandard_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('profstandard_id', sa.Integer(), nullable=True),
    sa.Column('qualification_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profstandard_id'], ['profstandard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profstandard_education_name'), 'profstandard_education', ['name'], unique=True)
    op.create_index(op.f('ix_profstandard_education_profstandard_id'), 'profstandard_education', ['profstandard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profstandard_education_profstandard_id'), table_name='profstandard_education')
    op.drop_index(op.f('ix_profstandard_education_name'), table_name='profstandard_education')
    op.drop_table('profstandard_education')
    op.drop_table('university')
    op.drop_table('parts_themes')
    op.drop_table('parts')
    op.drop_table('education_program')
    op.drop_table('ZYN')
    # ### end Alembic commands ###
