"""all tables

Revision ID: 61e72f3a2176
Revises: 
Create Date: 2018-12-09 01:38:01.482410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e72f3a2176'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profstandard',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code', 'label')
    )
    op.create_index(op.f('ix_profstandard_name'), 'profstandard', ['name'], unique=True)
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_name'), 'region', ['name'], unique=True)
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_name'), 'requirements', ['name'], unique=True)
    op.create_table('general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('stand_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stand_code'], ['profstandard.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_name'), 'general', ['name'], unique=True)
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['label'], ['profstandard.label'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_timestamp'), 'vacancies', ['timestamp'], unique=False)
    op.create_table('function',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('general_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['general_id'], ['general.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_name'), 'function', ['name'], unique=True)
    op.create_table('competence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('comp_type', sa.String(length=64), nullable=True),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['function.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competence_comp_type'), 'competence', ['comp_type'], unique=False)
    op.create_index(op.f('ix_competence_name'), 'competence', ['name'], unique=False)
    op.create_table('vacancy_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vac_id', sa.Integer(), nullable=True),
    sa.Column('competence', sa.Integer(), nullable=True),
    sa.Column('simularity', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('requirements_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competence'], ['competence.id'], ),
    sa.ForeignKeyConstraint(['requirements_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['vac_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_part')
    op.drop_index(op.f('ix_competence_name'), table_name='competence')
    op.drop_index(op.f('ix_competence_comp_type'), table_name='competence')
    op.drop_table('competence')
    op.drop_index(op.f('ix_function_name'), table_name='function')
    op.drop_table('function')
    op.drop_index(op.f('ix_vacancies_timestamp'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_general_name'), table_name='general')
    op.drop_table('general')
    op.drop_index(op.f('ix_requirements_name'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_region_name'), table_name='region')
    op.drop_table('region')
    op.drop_index(op.f('ix_profstandard_name'), table_name='profstandard')
    op.drop_table('profstandard')
    # ### end Alembic commands ###
