"""empty message

Revision ID: 62b8bdb00f45
Revises: 6e217d27b362
Create Date: 2018-12-16 16:54:21.525018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b8bdb00f45'
down_revision = '6e217d27b362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profstandard_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('profstandard_id', sa.Integer(), nullable=True),
    sa.Column('qualification_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profstandard_id'], ['profstandard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profstandard_post_name'), 'profstandard_post', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profstandard_post_name'), table_name='profstandard_post')
    op.drop_table('profstandard_post')
    # ### end Alembic commands ###
