"""empty message

Revision ID: 6e217d27b362
Revises: c12462e81841
Create Date: 2018-12-15 22:21:39.663640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e217d27b362'
down_revision = 'c12462e81841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('link', sa.String(length=128), nullable=True))
    op.add_column('vacancy', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'text')
    op.drop_column('vacancy', 'link')
    # ### end Alembic commands ###
