"""empty message

Revision ID: bc92eafed48b
Revises: c9929d72b45e
Create Date: 2019-02-16 21:42:36.559035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc92eafed48b'
down_revision = 'c9929d72b45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_classified_vacancy_profstandard_id'), 'classified_vacancy', ['profstandard_id'], unique=False)
    op.create_index(op.f('ix_classified_vacancy_vacancy_id'), 'classified_vacancy', ['vacancy_id'], unique=False)
    op.create_index(op.f('ix_general_function_profstandard_id'), 'general_function', ['profstandard_id'], unique=False)
    op.create_index(op.f('ix_match_part_profstandard_part_id'), 'match_part', ['profstandard_part_id'], unique=False)
    op.create_index(op.f('ix_match_part_similarity'), 'match_part', ['similarity'], unique=False)
    op.create_index(op.f('ix_match_part_vacancy_part_id'), 'match_part', ['vacancy_part_id'], unique=False)
    op.create_index(op.f('ix_profstandard_code'), 'profstandard', ['code'], unique=True)
    op.create_index(op.f('ix_profstandard_part_function_id'), 'profstandard_part', ['function_id'], unique=False)
    op.create_index(op.f('ix_profstandard_part_part_type_id'), 'profstandard_part', ['part_type_id'], unique=False)
    op.create_index(op.f('ix_profstandard_post_profstandard_id'), 'profstandard_post', ['profstandard_id'], unique=False)
    op.create_index(op.f('ix_vacancy_region_id'), 'vacancy', ['region_id'], unique=False)
    op.create_index(op.f('ix_vacancy_source_id'), 'vacancy', ['source_id'], unique=False)
    op.create_index(op.f('ix_vacancy_part_type_id'), 'vacancy_part', ['type_id'], unique=False)
    op.create_index(op.f('ix_vacancy_part_vacancy_id'), 'vacancy_part', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_part_vacancy_id'), table_name='vacancy_part')
    op.drop_index(op.f('ix_vacancy_part_type_id'), table_name='vacancy_part')
    op.drop_index(op.f('ix_vacancy_source_id'), table_name='vacancy')
    op.drop_index(op.f('ix_vacancy_region_id'), table_name='vacancy')
    op.drop_index(op.f('ix_profstandard_post_profstandard_id'), table_name='profstandard_post')
    op.drop_index(op.f('ix_profstandard_part_part_type_id'), table_name='profstandard_part')
    op.drop_index(op.f('ix_profstandard_part_function_id'), table_name='profstandard_part')
    op.drop_index(op.f('ix_profstandard_code'), table_name='profstandard')
    op.drop_index(op.f('ix_match_part_vacancy_part_id'), table_name='match_part')
    op.drop_index(op.f('ix_match_part_similarity'), table_name='match_part')
    op.drop_index(op.f('ix_match_part_profstandard_part_id'), table_name='match_part')
    op.drop_index(op.f('ix_general_function_profstandard_id'), table_name='general_function')
    op.drop_index(op.f('ix_classified_vacancy_vacancy_id'), table_name='classified_vacancy')
    op.drop_index(op.f('ix_classified_vacancy_profstandard_id'), table_name='classified_vacancy')
    # ### end Alembic commands ###
