"""empty message

Revision ID: c12462e81841
Revises: efb520db8180
Create Date: 2018-12-14 22:07:24.324990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12462e81841'
down_revision = 'efb520db8180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_function_name', table_name='function')
    op.create_index(op.f('ix_function_name'), 'function', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_function_name'), table_name='function')
    op.create_index('ix_function_name', 'function', ['name'], unique=1)
    # ### end Alembic commands ###
