"""empty message

Revision ID: c9929d72b45e
Revises: 62b8bdb00f45
Create Date: 2019-02-16 21:37:30.697283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9929d72b45e'
down_revision = '62b8bdb00f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_function_general_function_id'), 'function', ['general_function_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_function_general_function_id'), table_name='function')
    # ### end Alembic commands ###
