"""empty message

Revision ID: efb520db8180
Revises: 
Create Date: 2018-12-14 00:16:57.465204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb520db8180'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profstandard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('is_support', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_profstandard_name'), 'profstandard', ['name'], unique=True)
    op.create_table('profstandard_part_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profstandard_part_type_name'), 'profstandard_part_type', ['name'], unique=True)
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_name'), 'region', ['name'], unique=True)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('is_support', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_name'), 'source', ['name'], unique=True)
    op.create_table('vacancy_part_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_part_type_name'), 'vacancy_part_type', ['name'], unique=True)
    op.create_table('general_function',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('profstandard_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('qualification_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profstandard_id'], ['profstandard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_function_name'), 'general_function', ['name'], unique=True)
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_create_date'), 'vacancy', ['create_date'], unique=False)
    op.create_table('classified_vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('profstandard_id', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['profstandard_id'], ['profstandard.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('function',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('general_function_id', sa.Integer(), nullable=True),
    sa.Column('qualification_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['general_function_id'], ['general_function.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_name'), 'function', ['name'], unique=True)
    op.create_table('vacancy_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['vacancy_part_type.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profstandard_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('part_type_id', sa.Integer(), nullable=True),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['function.id'], ),
    sa.ForeignKeyConstraint(['part_type_id'], ['profstandard_part_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_part_id', sa.Integer(), nullable=True),
    sa.Column('profstandard_part_id', sa.Integer(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('enriched_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profstandard_part_id'], ['profstandard_part.id'], ),
    sa.ForeignKeyConstraint(['vacancy_part_id'], ['vacancy_part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_part')
    op.drop_table('profstandard_part')
    op.drop_table('vacancy_part')
    op.drop_index(op.f('ix_function_name'), table_name='function')
    op.drop_table('function')
    op.drop_table('classified_vacancy')
    op.drop_index(op.f('ix_vacancy_create_date'), table_name='vacancy')
    op.drop_table('vacancy')
    op.drop_index(op.f('ix_general_function_name'), table_name='general_function')
    op.drop_table('general_function')
    op.drop_index(op.f('ix_vacancy_part_type_name'), table_name='vacancy_part_type')
    op.drop_table('vacancy_part_type')
    op.drop_index(op.f('ix_source_name'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_region_name'), table_name='region')
    op.drop_table('region')
    op.drop_index(op.f('ix_profstandard_part_type_name'), table_name='profstandard_part_type')
    op.drop_table('profstandard_part_type')
    op.drop_index(op.f('ix_profstandard_name'), table_name='profstandard')
    op.drop_table('profstandard')
    # ### end Alembic commands ###
